name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        compiler: [gcc, clang]

    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2

    - name: Tests
      run: bash scripts/test.sh

  test-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libevent
        run: sudo apt install libevent-dev

      - name: Test the example server
        run: bash scripts/test-server.sh

  check-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download run-clang-format
        run: git submodule update --init run-clang-format

      - name: Check code formatting
        run: bash scripts/check-fmt.sh

  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt install doxygen graphviz

      - name: Build the docs
        run: bash scripts/docs.sh

      - name: Deploy the docs
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs/
